package com.infinitygear.api;

public enum FailureReason {
    NONE, NOT_GEAR, UNKNOWN_PROFILE, INVALID_ITEM, MALFORMED_IDENTITY, QUARANTINED,
    NOT_PRIMARY_THREAD, INVALID_BOOK, POLICY_REJECTED, PROVIDER_UNAVAILABLE, INVENTORY_FULL,
    STALE_INPUT, CANCELLED
}
